import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
EMAIL_TOKEN_EXPIRE_MIN = int(os.getenv("EMAIL_TOKEN_EXPIRE_MIN", 3))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))

SYNC_DATABASE_URL = DATABASE_URL.replace("+asyncpg", "+psycopg")

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

UNVERIFIED_USER_TTL_MIN = int(os.getenv("UNVERIFIED_USER_TTL_MIN"))
CLEANUP_INTERVAL_SECONDS = int(os.getenv("CLEANUP_INTERVAL_SECONDS"))

RATE_LIMIT_REDIS_URL = os.getenv("RATE_LIMIT_REDIS_URL")